-- 25.1: GARANTIR QUE EXCLUSÕES ENVIEM O ID COMPLETO PARA O REALTIME
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER TABLE public.signals REPLICA IDENTITY FULL;
ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.signal_types REPLICA IDENTITY FULL;
ALTER TABLE public.notifications REPLICA IDENTITY FULL;
ALTER TABLE public.conversations REPLICA IDENTITY FULL;
